export const workoutTemplates = [
  {
    title: "AB Iniciante",
    description: "Treino AB simples para quem estÃ¡ comeÃ§ando.",
    focuses: {
      "Treino A": "Superiores",
      "Treino B": "Inferiores e AbdÃ´men",
    },
    exercises: [
      {
        workout_day: "Treino A",
        name: "Supino mÃ¡quina",
        sets: "3",
        reps: "10-12",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "Puxada alta",
        sets: "3",
        reps: "10-12",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "Desenvolvimento de ombros",
        sets: "3",
        reps: "10-12",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "Rosca direta",
        sets: "2",
        reps: "12",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "TrÃ­ceps pulley",
        sets: "2",
        reps: "12",
        load: "",
      },

      {
        workout_day: "Treino B",
        name: "Agachamento livre ou guiado",
        sets: "3",
        reps: "10-12",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Leg press",
        sets: "3",
        reps: "10-12",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Cadeira extensora",
        sets: "3",
        reps: "12",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Mesa flexora",
        sets: "3",
        reps: "12",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Prancha abdominal",
        sets: "3",
        reps: "30s",
        load: "",
      },
    ],
  },
  {
    title: "ABC Iniciante",
    description: "Treino ABC com volume moderado para iniciantes.",
    focuses: {
      "Treino A": "Peito, Ombros e TrÃ­ceps",
      "Treino B": "Costas e BÃ­ceps",
      "Treino C": "Pernas e AbdÃ´men",
    },
    exercises: [
      {
        workout_day: "Treino A",
        name: "Supino mÃ¡quina",
        sets: "3",
        reps: "10-12",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "Supino inclinado com halteres",
        sets: "3",
        reps: "10",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "Desenvolvimento de ombros",
        sets: "3",
        reps: "10-12",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "TrÃ­ceps pulley",
        sets: "3",
        reps: "12",
        load: "",
      },

      {
        workout_day: "Treino B",
        name: "Puxada alta",
        sets: "3",
        reps: "10-12",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Remada baixa",
        sets: "3",
        reps: "10-12",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Pulldown",
        sets: "3",
        reps: "12",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Rosca direta",
        sets: "3",
        reps: "12",
        load: "",
      },

      {
        workout_day: "Treino C",
        name: "Agachamento guiado",
        sets: "3",
        reps: "10-12",
        load: "",
      },
      {
        workout_day: "Treino C",
        name: "Leg press",
        sets: "3",
        reps: "10-12",
        load: "",
      },
      {
        workout_day: "Treino C",
        name: "Cadeira extensora",
        sets: "3",
        reps: "12",
        load: "",
      },
      {
        workout_day: "Treino C",
        name: "Mesa flexora",
        sets: "3",
        reps: "12",
        load: "",
      },
      {
        workout_day: "Treino C",
        name: "Abdominal mÃ¡quina",
        sets: "3",
        reps: "15",
        load: "",
      },
    ],
  },
  {
    title: "ABC Hipertrofia",
    description: "Treino ABC focado em hipertrofia muscular.",
    focuses: {
      "Treino A": "Peito e TrÃ­ceps",
      "Treino B": "Costas e BÃ­ceps",
      "Treino C": "Pernas e AbdÃ´men",
    },
    exercises: [
      {
        workout_day: "Treino A",
        name: "Supino reto",
        sets: "4",
        reps: "8-10",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "Supino inclinado",
        sets: "3",
        reps: "10-12",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "Crucifixo",
        sets: "3",
        reps: "12",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "TrÃ­ceps corda",
        sets: "3",
        reps: "10-12",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "TrÃ­ceps testa",
        sets: "3",
        reps: "10-12",
        load: "",
      },

      {
        workout_day: "Treino B",
        name: "Puxada alta",
        sets: "4",
        reps: "8-10",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Remada baixa",
        sets: "3",
        reps: "10-12",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Remada unilateral",
        sets: "3",
        reps: "10",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Rosca direta",
        sets: "3",
        reps: "10-12",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Rosca martelo",
        sets: "3",
        reps: "10-12",
        load: "",
      },

      {
        workout_day: "Treino C",
        name: "Agachamento livre",
        sets: "4",
        reps: "8-10",
        load: "",
      },
      {
        workout_day: "Treino C",
        name: "Leg press",
        sets: "4",
        reps: "10-12",
        load: "",
      },
      {
        workout_day: "Treino C",
        name: "Cadeira extensora",
        sets: "3",
        reps: "12",
        load: "",
      },
      {
        workout_day: "Treino C",
        name: "Mesa flexora",
        sets: "3",
        reps: "12",
        load: "",
      },
      {
        workout_day: "Treino C",
        name: "Abdominal prancha",
        sets: "3",
        reps: "30-45s",
        load: "",
      },
    ],
  },
  {
    title: "ABC AvanÃ§ado",
    description: "Treino ABC com maior intensidade e volume.",
    focuses: {
      "Treino A": "Peito, Ombros e TrÃ­ceps",
      "Treino B": "Costas, TrapÃ©zio e BÃ­ceps",
      "Treino C": "Pernas completas",
    },
    exercises: [
      {
        workout_day: "Treino A",
        name: "Supino reto",
        sets: "4",
        reps: "6-8",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "Supino inclinado com halteres",
        sets: "4",
        reps: "8-10",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "Crossover",
        sets: "3",
        reps: "12-15",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "Desenvolvimento militar",
        sets: "4",
        reps: "8-10",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "ElevaÃ§Ã£o lateral",
        sets: "4",
        reps: "12",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "TrÃ­ceps francÃªs",
        sets: "3",
        reps: "10-12",
        load: "",
      },

      {
        workout_day: "Treino B",
        name: "Barra fixa ou puxada alta",
        sets: "4",
        reps: "6-10",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Remada curvada",
        sets: "4",
        reps: "8-10",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Remada cavalinho",
        sets: "3",
        reps: "10",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Encolhimento",
        sets: "4",
        reps: "12",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Rosca direta barra",
        sets: "3",
        reps: "8-10",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Rosca alternada",
        sets: "3",
        reps: "10-12",
        load: "",
      },

      {
        workout_day: "Treino C",
        name: "Agachamento livre",
        sets: "5",
        reps: "6-8",
        load: "",
      },
      {
        workout_day: "Treino C",
        name: "Leg press",
        sets: "4",
        reps: "10",
        load: "",
      },
      {
        workout_day: "Treino C",
        name: "Stiff",
        sets: "4",
        reps: "8-10",
        load: "",
      },
      {
        workout_day: "Treino C",
        name: "Cadeira extensora",
        sets: "3",
        reps: "12-15",
        load: "",
      },
      {
        workout_day: "Treino C",
        name: "Mesa flexora",
        sets: "3",
        reps: "12",
        load: "",
      },
      {
        workout_day: "Treino C",
        name: "Panturrilha em pÃ©",
        sets: "5",
        reps: "12-15",
        load: "",
      },
    ],
  },
  {
    title: "ABCD Normal",
    description: "DivisÃ£o ABCD equilibrada para evoluÃ§Ã£o muscular.",
    focuses: {
      "Treino A": "Peito e TrÃ­ceps",
      "Treino B": "Costas e BÃ­ceps",
      "Treino C": "Pernas",
      "Treino D": "Ombros e AbdÃ´men",
    },
    exercises: [
      {
        workout_day: "Treino A",
        name: "Supino reto",
        sets: "4",
        reps: "8-10",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "Supino inclinado",
        sets: "3",
        reps: "10",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "Crucifixo",
        sets: "3",
        reps: "12",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "TrÃ­ceps pulley",
        sets: "3",
        reps: "10-12",
        load: "",
      },

      {
        workout_day: "Treino B",
        name: "Puxada alta",
        sets: "4",
        reps: "8-10",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Remada baixa",
        sets: "3",
        reps: "10-12",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Pulldown",
        sets: "3",
        reps: "12",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Rosca direta",
        sets: "3",
        reps: "10-12",
        load: "",
      },

      {
        workout_day: "Treino C",
        name: "Agachamento",
        sets: "4",
        reps: "8-10",
        load: "",
      },
      {
        workout_day: "Treino C",
        name: "Leg press",
        sets: "4",
        reps: "10-12",
        load: "",
      },
      {
        workout_day: "Treino C",
        name: "Stiff",
        sets: "3",
        reps: "10",
        load: "",
      },
      {
        workout_day: "Treino C",
        name: "Panturrilha sentado",
        sets: "4",
        reps: "12-15",
        load: "",
      },

      {
        workout_day: "Treino D",
        name: "Desenvolvimento com halteres",
        sets: "4",
        reps: "8-10",
        load: "",
      },
      {
        workout_day: "Treino D",
        name: "ElevaÃ§Ã£o lateral",
        sets: "3",
        reps: "12",
        load: "",
      },
      {
        workout_day: "Treino D",
        name: "Face pull",
        sets: "3",
        reps: "12-15",
        load: "",
      },
      {
        workout_day: "Treino D",
        name: "Abdominal infra",
        sets: "3",
        reps: "15",
        load: "",
      },
    ],
  },
  {
    title: "ABCD AvanÃ§ado",
    description: "DivisÃ£o ABCD com maior volume e intensidade.",
    focuses: {
      "Treino A": "Peito",
      "Treino B": "Costas",
      "Treino C": "Pernas",
      "Treino D": "Ombros e BraÃ§os",
    },
    exercises: [
      {
        workout_day: "Treino A",
        name: "Supino reto",
        sets: "4",
        reps: "6-8",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "Supino inclinado com halteres",
        sets: "4",
        reps: "8-10",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "Paralelas",
        sets: "3",
        reps: "8-12",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "Crossover",
        sets: "3",
        reps: "12-15",
        load: "",
      },

      {
        workout_day: "Treino B",
        name: "Barra fixa ou puxada alta",
        sets: "4",
        reps: "6-10",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Remada curvada",
        sets: "4",
        reps: "8",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Remada unilateral",
        sets: "3",
        reps: "10",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Pulldown",
        sets: "3",
        reps: "12",
        load: "",
      },

      {
        workout_day: "Treino C",
        name: "Agachamento livre",
        sets: "5",
        reps: "6-8",
        load: "",
      },
      {
        workout_day: "Treino C",
        name: "Leg press",
        sets: "4",
        reps: "10",
        load: "",
      },
      {
        workout_day: "Treino C",
        name: "Stiff",
        sets: "4",
        reps: "8-10",
        load: "",
      },
      {
        workout_day: "Treino C",
        name: "Mesa flexora",
        sets: "3",
        reps: "12",
        load: "",
      },

      {
        workout_day: "Treino D",
        name: "Desenvolvimento militar",
        sets: "4",
        reps: "6-8",
        load: "",
      },
      {
        workout_day: "Treino D",
        name: "ElevaÃ§Ã£o lateral",
        sets: "4",
        reps: "12",
        load: "",
      },
      {
        workout_day: "Treino D",
        name: "Rosca direta",
        sets: "3",
        reps: "8-10",
        load: "",
      },
      {
        workout_day: "Treino D",
        name: "Rosca martelo",
        sets: "3",
        reps: "10-12",
        load: "",
      },
      {
        workout_day: "Treino D",
        name: "TrÃ­ceps testa",
        sets: "3",
        reps: "8-10",
        load: "",
      },
      {
        workout_day: "Treino D",
        name: "TrÃ­ceps corda",
        sets: "3",
        reps: "12",
        load: "",
      },
    ],
  },
  {
    title: "ABCDE AvanÃ§ado",
    description: "Treino ABCDE com foco especÃ­fico por grupo muscular.",
    focuses: {
      "Treino A": "Peito",
      "Treino B": "Costas",
      "Treino C": "Pernas",
      "Treino D": "Ombros",
      "Treino E": "BraÃ§os e AbdÃ´men",
    },
    exercises: [
      {
        workout_day: "Treino A",
        name: "Supino reto",
        sets: "4",
        reps: "6-8",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "Supino inclinado",
        sets: "4",
        reps: "8-10",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "Crossover",
        sets: "4",
        reps: "12",
        load: "",
      },

      {
        workout_day: "Treino B",
        name: "Puxada alta",
        sets: "4",
        reps: "8-10",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Remada curvada",
        sets: "4",
        reps: "8",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Remada baixa",
        sets: "4",
        reps: "10-12",
        load: "",
      },

      {
        workout_day: "Treino C",
        name: "Agachamento livre",
        sets: "5",
        reps: "6-8",
        load: "",
      },
      {
        workout_day: "Treino C",
        name: "Leg press",
        sets: "4",
        reps: "10",
        load: "",
      },
      {
        workout_day: "Treino C",
        name: "Stiff",
        sets: "4",
        reps: "8-10",
        load: "",
      },
      {
        workout_day: "Treino C",
        name: "Panturrilha em pÃ©",
        sets: "5",
        reps: "12-15",
        load: "",
      },

      {
        workout_day: "Treino D",
        name: "Desenvolvimento militar",
        sets: "4",
        reps: "6-8",
        load: "",
      },
      {
        workout_day: "Treino D",
        name: "ElevaÃ§Ã£o lateral",
        sets: "4",
        reps: "12",
        load: "",
      },
      {
        workout_day: "Treino D",
        name: "Face pull",
        sets: "4",
        reps: "12-15",
        load: "",
      },

      {
        workout_day: "Treino E",
        name: "Rosca direta",
        sets: "4",
        reps: "8-10",
        load: "",
      },
      {
        workout_day: "Treino E",
        name: "Rosca martelo",
        sets: "3",
        reps: "10-12",
        load: "",
      },
      {
        workout_day: "Treino E",
        name: "TrÃ­ceps testa",
        sets: "4",
        reps: "8-10",
        load: "",
      },
      {
        workout_day: "Treino E",
        name: "Abdominal prancha",
        sets: "4",
        reps: "40-60s",
        load: "",
      },
    ],
  },
  {
    title: "Full Body Iniciante",
    description: "Treino de corpo inteiro ideal para iniciantes.",
    focuses: {
      "Full Body": "Corpo inteiro",
    },
    exercises: [
      {
        workout_day: "Full Body",
        name: "Agachamento livre ou guiado",
        sets: "3",
        reps: "10-12",
        load: "",
      },
      {
        workout_day: "Full Body",
        name: "Supino mÃ¡quina",
        sets: "3",
        reps: "10-12",
        load: "",
      },
      {
        workout_day: "Full Body",
        name: "Puxada alta",
        sets: "3",
        reps: "10-12",
        load: "",
      },
      {
        workout_day: "Full Body",
        name: "Desenvolvimento de ombros",
        sets: "3",
        reps: "10-12",
        load: "",
      },
      {
        workout_day: "Full Body",
        name: "Leg press",
        sets: "3",
        reps: "10-12",
        load: "",
      },
      {
        workout_day: "Full Body",
        name: "Prancha abdominal",
        sets: "3",
        reps: "30s",
        load: "",
      },
    ],
  },
  {
    title: "Full Body IntermediÃ¡rio",
    description: "Treino de corpo inteiro com volume moderado.",
    focuses: {
      "Full Body": "Corpo inteiro e condicionamento",
    },
    exercises: [
      {
        workout_day: "Full Body",
        name: "Agachamento livre",
        sets: "4",
        reps: "8-10",
        load: "",
      },
      {
        workout_day: "Full Body",
        name: "Supino reto",
        sets: "4",
        reps: "8-10",
        load: "",
      },
      {
        workout_day: "Full Body",
        name: "Remada baixa",
        sets: "4",
        reps: "10",
        load: "",
      },
      {
        workout_day: "Full Body",
        name: "Desenvolvimento militar",
        sets: "3",
        reps: "10",
        load: "",
      },
      {
        workout_day: "Full Body",
        name: "Stiff",
        sets: "3",
        reps: "10",
        load: "",
      },
      {
        workout_day: "Full Body",
        name: "Rosca direta",
        sets: "3",
        reps: "12",
        load: "",
      },
      {
        workout_day: "Full Body",
        name: "TrÃ­ceps pulley",
        sets: "3",
        reps: "12",
        load: "",
      },
      {
        workout_day: "Full Body",
        name: "Prancha abdominal",
        sets: "3",
        reps: "45s",
        load: "",
      },
    ],
  },
  {
    title: "PPL - Push Pull Legs",
    description: "DivisÃ£o Push, Pull e Legs.",
    focuses: {
      "Treino A": "Push - Peito, Ombros e TrÃ­ceps",
      "Treino B": "Pull - Costas e BÃ­ceps",
      "Treino C": "Legs - Pernas",
    },
    exercises: [
      {
        workout_day: "Treino A",
        name: "Supino reto",
        sets: "4",
        reps: "8-10",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "Desenvolvimento militar",
        sets: "3",
        reps: "8-10",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "ElevaÃ§Ã£o lateral",
        sets: "3",
        reps: "12",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "TrÃ­ceps corda",
        sets: "3",
        reps: "10-12",
        load: "",
      },

      {
        workout_day: "Treino B",
        name: "Puxada alta",
        sets: "4",
        reps: "8-10",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Remada baixa",
        sets: "3",
        reps: "10-12",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Face pull",
        sets: "3",
        reps: "12",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Rosca direta",
        sets: "3",
        reps: "10-12",
        load: "",
      },

      {
        workout_day: "Treino C",
        name: "Agachamento",
        sets: "4",
        reps: "8-10",
        load: "",
      },
      {
        workout_day: "Treino C",
        name: "Leg press",
        sets: "4",
        reps: "10-12",
        load: "",
      },
      {
        workout_day: "Treino C",
        name: "Stiff",
        sets: "3",
        reps: "10-12",
        load: "",
      },
      {
        workout_day: "Treino C",
        name: "Panturrilha em pÃ©",
        sets: "4",
        reps: "12-15",
        load: "",
      },
    ],
  },
  {
    title: "PPL AvanÃ§ado",
    description: "Push Pull Legs com maior volume para praticantes avanÃ§ados.",
    focuses: {
      "Treino A": "Push pesado",
      "Treino B": "Pull pesado",
      "Treino C": "Legs pesado",
    },
    exercises: [
      {
        workout_day: "Treino A",
        name: "Supino reto",
        sets: "5",
        reps: "5-8",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "Supino inclinado com halteres",
        sets: "4",
        reps: "8-10",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "Desenvolvimento militar",
        sets: "4",
        reps: "6-8",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "ElevaÃ§Ã£o lateral",
        sets: "4",
        reps: "12-15",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "TrÃ­ceps testa",
        sets: "4",
        reps: "8-10",
        load: "",
      },

      {
        workout_day: "Treino B",
        name: "Barra fixa",
        sets: "5",
        reps: "6-10",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Remada curvada",
        sets: "4",
        reps: "6-8",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Remada baixa",
        sets: "4",
        reps: "10",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Face pull",
        sets: "4",
        reps: "12-15",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Rosca direta",
        sets: "4",
        reps: "8-10",
        load: "",
      },

      {
        workout_day: "Treino C",
        name: "Agachamento livre",
        sets: "5",
        reps: "5-8",
        load: "",
      },
      {
        workout_day: "Treino C",
        name: "Leg press",
        sets: "4",
        reps: "10",
        load: "",
      },
      {
        workout_day: "Treino C",
        name: "Stiff",
        sets: "4",
        reps: "8-10",
        load: "",
      },
      {
        workout_day: "Treino C",
        name: "Afundo com halteres",
        sets: "3",
        reps: "10 cada perna",
        load: "",
      },
      {
        workout_day: "Treino C",
        name: "Panturrilha em pÃ©",
        sets: "5",
        reps: "12-15",
        load: "",
      },
    ],
  },
  {
    title: "Emagrecimento e Condicionamento",
    description: "Treino com musculaÃ§Ã£o e exercÃ­cios metabÃ³licos.",
    focuses: {
      "Treino A": "ForÃ§a geral",
      "Treino B": "Condicionamento",
      "Treino C": "Pernas e Core",
    },
    exercises: [
      {
        workout_day: "Treino A",
        name: "Agachamento goblet",
        sets: "3",
        reps: "12",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "Supino mÃ¡quina",
        sets: "3",
        reps: "12",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "Puxada alta",
        sets: "3",
        reps: "12",
        load: "",
      },
      {
        workout_day: "Treino A",
        name: "Prancha abdominal",
        sets: "3",
        reps: "30-45s",
        load: "",
      },

      {
        workout_day: "Treino B",
        name: "Esteira ou bike",
        sets: "1",
        reps: "15-20min",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Burpee adaptado",
        sets: "3",
        reps: "10",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Kettlebell swing ou remada alta",
        sets: "3",
        reps: "12",
        load: "",
      },
      {
        workout_day: "Treino B",
        name: "Abdominal bicicleta",
        sets: "3",
        reps: "20",
        load: "",
      },

      {
        workout_day: "Treino C",
        name: "Leg press",
        sets: "4",
        reps: "12",
        load: "",
      },
      {
        workout_day: "Treino C",
        name: "Cadeira extensora",
        sets: "3",
        reps: "15",
        load: "",
      },
      {
        workout_day: "Treino C",
        name: "Mesa flexora",
        sets: "3",
        reps: "15",
        load: "",
      },
      {
        workout_day: "Treino C",
        name: "Abdominal infra",
        sets: "3",
        reps: "15",
        load: "",
      },
    ],
  },
];
